all: experiment_1 experiment_2 experiment_3 experiment_4 experiment_5

attribute_selection:
	./attribute_selection.sh


experiment_1: clean_1
	./experiment_1.sh

experiment_2: clean_2
	./experiment_2.sh

experiment_3: clean_3
	./experiment_3.sh

experiment_4: clean_4
	./experiment_4.sh

experiment_5: clean_5
	./experiment_5.sh

clean_1:
	rm -rf experiment_1

clean_2:
	rm -rf experiment_2

clean_3:
	rm -rf experiment_3

clean_4:
	rm -rf experiment_4

clean_5:
	rm -rf experiment_5